# openapi: 3.0.2
# info:
#   version: 1.0.17
#   title: Health Check API - OpenAPI 3.0
#   description: Check system status with essential real-time metrics.
#   termsOfService: 'http://swagger.io/terms/'
#   contact:
#     email: apiteam@swagger.io
#   license:
#     name: Apache 2.0
#     url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
# tags:
#   - name: veecode-platform
#     description: Made 
#     externalDocs:
#       description: made with Devportal
#       url: 'http://localhost:5000'

# # Definition of API paths/endpoints
# paths:
#   /:
#     get:
#       summary: Health Check Status
#       description: Real-time system status check.

# # Reusable components (schemas, security, etc.)
# components:
#   schemas:
#   securitySchemes:
#     apistore_auth:
#     api_key:

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-health-check
  title: api-health-check
  publishedAt: "2023-09-26 12:13:35"
  description: 'Check system status with essential real-time metrics.'
  tags:
    - api
    - node
    - platform
spec:
  type: openapi
  lifecycle: production
  owner: admin
  definition: |-
    openapi: 3.0.2
    info:
        description: 'Check system status with essential real-time metrics.'
        version: 1.0.2
        title: api-health-check
        termsOfService: http://swagger.io/terms/
        contact:
            email: apiteam@swagger.io
        license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
    servers:
        - url: https://localhost:5000
    tags:
        - name: spec
          description: Health
          externalDocs:
            description: Find out more
            url: http://swagger.io
    paths: 
      	/:
	    get:
	      summary: Health Check Status
	      description: Real-time system status check.
    components: {}
